### PR TITLE
snmpusm.c: Improve usm_read_user()'s error handling

### LINKED ISSUE #734: snmpusm.c:4295:34: runtime error: null pointer passed as argument 1, which is declared to never be null
```
$ cp fuzz_out/default/crashes/id:000003* fuzz_input.conf.txt && ./agent/snmpd -fd -C -r -c "fuzz_input.conf.txt"
snmpusm.c:4295:34: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/stdlib.h:106:33: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior snmpusm.c:4295:34 in 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==207614==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f1aa7e4ad5b bp 0x00000000000a sp 0x7ffeed93d9e0 T0)
==207614==The signal is caused by a READ memory access.
==207614==Hint: address points to the zero page.
    #0 0x7f1aa7e4ad5b in __GI_____strtol_l_internal stdlib/../stdlib/strtol_l.c:291:10
    #1 0x555e6b986d15 in __interceptor_strtol (/home/user/Desktop/net-snmp/agent/.libs/snmpd+0x96d15) (BuildId: 805b58d3d7b3884d608aeb92ae1f51dd03baf716)
    #2 0x7f1aa8e8848e in atoi /usr/include/stdlib.h:364:16
    #3 0x7f1aa8e8848e in usm_read_user /home/user/Desktop/net-snmp/snmplib/snmpusm.c:4295:29
    #4 0x7f1aa8e8848e in usm_parse_config_usmUser /home/user/Desktop/net-snmp/snmplib/snmpusm.c:4355:12
    #5 0x7f1aa8bb4dd2 in run_config_handler /home/user/Desktop/net-snmp/snmplib/read_config.c:565:23
    #6 0x7f1aa8baed81 in read_config /home/user/Desktop/net-snmp/snmplib/read_config.c:990:17
    #7 0x7f1aa8bbd15e in read_configs_optional /home/user/Desktop/net-snmp/snmplib/read_config.c:1048:18
    #8 0x7f1aa8bbdbdd in read_configs /home/user/Desktop/net-snmp/snmplib/read_config.c:1079:15
    #9 0x555e6b9dc294 in main /home/user/Desktop/net-snmp/agent/snmpd.c:909:5
    #10 0x7f1aa7e23a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #11 0x7f1aa7e23b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #12 0x555e6b9167b4 in _start (/home/user/Desktop/net-snmp/agent/.libs/snmpd+0x267b4) (BuildId: 805b58d3d7b3884d608aeb92ae1f51dd03baf716)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV stdlib/../stdlib/strtol_l.c:291:10 in __GI_____strtol_l_internal
==207614==ABORTING
```
[fuzz_input.conf.txt](https://github.com/net-snmp/net-snmp/files/12922898/fuzz_input.conf.txt)

### PR DESCRIPTION
**Pull request by moshekaplan**
Adds additional validation to snmpusm.c.
Fixes #734.

### CODE REVIEW

**Comment by moshekaplan** [comment]
Note: The reason I call this a partial fix is because it only added validation for two additional fields. Further fields are still not validated to be present.

**Comment by moshekaplan** [comment]
Note: This may also fix #733

File: snmplib/snmpusm.c [hunk 1]
```diff
@@ -4339,8 +4384,24 @@ usm_read_user(const char *line)
...
+
+    /*
+     * set the lcd entry for this engineID to the minimum boots/time
+     * values so that its a known engineid and won't return a report pdu.
+     * This is mostly important when receiving v3 traps so that the usm
+     * will at least continue processing them.
+     * Note: We do this at the end so that it only runs if the parsing
+     * was successful
+     */
+    set_enginetime(user->engineID, user->engineIDLen, 1, 0, 0);
```
Comment (bvanassche) [inline snmplib/snmpusm.c:4403]: Why to move this call to the end? I think this involves a behavior change and I'm not sure that behavior change is correct. How about preserving all the if (line == NULL) checks and moving the set_enginetime() call back to its original location?

**Review by bvanassche — CHANGES_REQUESTED** [review]

File: snmplib/snmpusm.c (hunk 1 above)
Comment (moshekaplan) [reply snmplib/snmpusm.c:4403]: I moved the call to the end because I didn't want to call `set_enginetime` and set it to an erroneous value if the line ends up being discarded due to a later required configuration value not being present. If you think it should be moved back up, even if the call to `usm_read_user` returns NULL, please confirm, and I will do so.

**Comment by bvanassche** [comment]
Thanks for the patch!
